<a href="https://colab.research.google.com/github/mbmarcin/ml_/blob/main/standardization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
# example of a normalization
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler
# define data
data = asarray([[1000, 10],
				[8, 0.05],
				[50, 0.005],
				[88, 0.07],
				[4, 0.1]])
print(data)
# define min max scaler
scaler = MinMaxScaler()
# transform data
scaled = scaler.fit_transform(data)
print(scaled)

[[1.0e+03 1.0e+01]
 [8.0e+00 5.0e-02]
 [5.0e+01 5.0e-03]
 [8.8e+01 7.0e-02]
 [4.0e+00 1.0e-01]]
[[1.         1.        ]
 [0.00401606 0.00450225]
 [0.04618474 0.        ]
 [0.08433735 0.00650325]
 [0.         0.00950475]]


In [21]:
# perform a robust scaler transform of the dataset
# define standard scaler
scaler = StandardScaler()
# transform data
scaled2 = scaler.fit_transform(data)
x = np.absolute(scaled2)
print(x)

[[1.99368963 1.99993972]
 [0.57480402 0.50155622]
 [0.46605732 0.51286952]
 [0.36766744 0.49652809]
 [0.58516085 0.48898589]]


In [23]:
np.sum(x, axis=0)

array([3.98737926, 3.99987943])